module.exports = {
  docsSidebar: [
    'introduction',
    'quickstart',
    'advanced-usage',
    'rationale',
    {
      type: 'category',
      label: 'Overview',
      items: [
        {
          type: 'autogenerated',
          dirName: 'overview',
        },
      ],
    },
    'roadmap',
    'changelog',
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};
